version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container2
    environment:
      MYSQL_ROOT_PASSWORD: ashok
      MYSQL_DATABASE: ai_assistant
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - ashok-nw

  springboot:
    build:
      context: ./spring_ai-testing
      dockerfile: Dockerfile
    container_name: springboot-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_USER: root
      DB_PASSWORD: ashok
      OPENAI_API_KEY: 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
    networks:
      - ashok-nw

  


volumes:
  mysqldata:

networks:
  ashok-nw:
    driver: bridge
