version: '3.8'

services:
  

  react:
    build:
      context: ./text-to-speech
      dockerfile: Dockerfile 
    container_name: react-app
    ports:
      - "3000:3000"
    networks:
      - ashok-nw
  
volumes:
  mysqldata:

networks:
  ashok-nw:
    driver: bridge
